package com.learning.roomdatabasebasics;

import androidx.room.Database;
import androidx.room.RoomDatabase;

//It specifies that the database has one entity, which is the "Person" table, and it is the first version of this database.
//Room will create and manage a table in the SQLite database for the "Person" entity.
@Database(entities = {Person.class}, version = 1)
//an abstract class that serves as the database holder and entry point for accessing a SQLite database in an Android application
//PersonDatabase is a crucial component in the Room Persistence Library for managing and providing access to your SQLite database in an Android application.
public abstract class PersonDatabase extends RoomDatabase {

    //The abstract keyword indicates that this method is declared but not implemented in the current class.
    //This method is intended to be implemented in subclasses of the RoomDatabase class, which is typical for methods that retrieve Data Access Object (DAO) instances.
    //method would typically return an instance of a concrete class generated by Room that implements the PersonDAO interface.
    //This class is automatically generated by Room to provide the database access methods defined in your PersonDAO interface.
    public abstract PersonDAO getPersonDAO();
}
