package com.learning.roomdatabasebasics;

import androidx.room.ColumnInfo;
import androidx.room.Entity;
import androidx.room.Ignore;
import androidx.room.PrimaryKey;

//defining a class as an entity,
// indicating that it should be mapped to a database table named "Person.
@Entity(tableName = "Person")
public class Person {

    // it indicates that the field id in your entity class should be stored in a database column named "person_id."
    @ColumnInfo(name="person_id")

    //This annotation specifies that the id field is the primary key of the database table.
    //primary key column will be automatically generated by the database when new records are inserted.
    @PrimaryKey(autoGenerate = true)
    int id;

    // It indicates that the name field should be stored in a database column named "name."
    @ColumnInfo(name = "name")
    String name;

    //indicates that the age field should be stored in a database column named "age."
    @ColumnInfo(name ="age")
    String age;

    @Ignore
    //empty Constructor
    public Person(){


    }

    //Constructor with arguments
    public Person(String name, String age) {
        this.name = name;
        this.age = age;
        this.id = 0;
    }

    //getters and setter

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getAge() {
        return age;
    }

    public void setAge(String age) {
        this.age = age;
    }
}
